//! Top level documentation
mod alignment;
mod analysis_window;
mod audio_signal;
pub mod audio_utils;
pub mod command_line_utils;
mod comparison_patches_selector;
pub mod constants;
mod convolution_2d;
mod envelope;
pub mod equivalent_rectangular_bandwidth;
mod fast_fourier_transform;
mod fft_manager;
pub mod gammatone_filterbank;
mod gammatone_spectrogram_builder;
mod image_patch_creator;
pub mod math_utils;
mod neurogram_similiarity_index_measure;
pub mod output_utils;
mod patch_creator;
mod patch_similarity_comparator;
mod path_pair;
mod rms_vad;
mod signal_filter;
pub mod similarity_result;
mod similarity_to_quality_mapper;
mod spectrogram;
mod spectrogram_builder;
mod speech_similarity_to_quality_mapper;
mod support_vector_regression_model;
mod svr_similarity_to_quality_mapper;
mod tflite_quality_mapper;
mod vad_patch_creator;
mod visqol;
mod visqol_error;
pub mod visqol_manager;
mod wav_reader;
mod xcorr;

#[cfg(test)]
mod test_utility;
